# Project
version=1.2.0
group=com.wnyyy.wanderingpets
java_version=25

# Common
minecraft_version=26.1
mod_name=Wandering Pets
mod_author=wnyyy
mod_id=wanderingpets
license=GPL-3.0
credits=
description=Configurable mod to disable tamed wolves, parrots, and cats from following the player
minecraft_version_range=[26.1, 26.1.2]

neo_form_version=26.1.2-1

fabric_version=0.145.1+26.1
fabric_loader_version=0.19.2

neoforge_version=26.1.2.7-beta
neoforge_loader_version_range=[4,)

org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false