modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]
modId="wanderingpets"
version="${mod_version}"
displayName="Wandering Pets"
credits="A continuation of the Independent Pets by lizin5ths"
authors="outurnate"
description='''
Configurable mod to disable tamed wolves, parrots, and cats from following the player
'''
[[mixins]]
config="wanderingpets.mixins.json"